-- Monthly Customer Total Sales
WITH 

    DIM_CUSTOMER AS
    (
        SELECT * FROM {{ ref('DIM_CUSTOMER') }}
    ),

    DIM_DATE AS
    (
        SELECT * FROM {{ ref('DIM_DATE') }}
    ),

    FACT_SALES AS
    (
        SELECT * FROM {{ ref('FACT_SALES') }}
    ),

    MONTHLY_SALES AS
    (
        SELECT 

            DIM_DATE.YEAR,
            DIM_DATE.MONTH,
            FACT_SALES.CUSTOMER_KEY,
            DIM_CUSTOMER.CUSTOMER_NAME,
            ROUND(SUM(FACT_SALES.SALES),3) AS MONTHLY_SALES

        FROM FACT_SALES

        LEFT JOIN DIM_CUSTOMER
            ON FACT_SALES.CUSTOMER_KEY = DIM_CUSTOMER.CUSTOMER_ID

        LEFT JOIN DIM_DATE
            ON FACT_SALES.ORDER_DATE_KEY = DIM_DATE.DATE_KEY

        GROUP BY DIM_DATE.YEAR, DIM_DATE.MONTH, FACT_SALES.CUSTOMER_KEY, DIM_CUSTOMER.CUSTOMER_NAME
        ORDER BY DIM_DATE.YEAR, DIM_DATE.MONTH, FACT_SALES.CUSTOMER_KEY, DIM_CUSTOMER.CUSTOMER_NAME
    )

SELECT * 
FROM MONTHLY_SALES

