-- Profitability_by_Location

WITH 

    DIM_LOCATION AS (
        SELECT * FROM {{ ref('DIM_LOCATION') }}
    ),

    FACT_SALES AS (
        SELECT * FROM {{ ref('FACT_SALES') }}
    ),

    LOCATION_PROFITS AS (
        SELECT

            DIM_LOCATION.COUNTRY,
            DIM_LOCATION.STATE,
            DIM_LOCATION.CITY,
            DIM_LOCATION.REGION,
            DIM_LOCATION.POSTAL_CODE,
            SUM(FACT_SALES.PROFIT) AS TOTAL_PROFIT

        FROM FACT_SALES
        LEFT JOIN DIM_LOCATION 
            ON FACT_SALES.LOCATION_SK = DIM_LOCATION.LOCATION_SK

        GROUP BY 
             DIM_LOCATION.COUNTRY, DIM_LOCATION.STATE, DIM_LOCATION.CITY, DIM_LOCATION.REGION,DIM_LOCATION.POSTAL_CODE
    )

SELECT *
FROM LOCATION_PROFITS
ORDER BY TOTAL_PROFIT DESC
