-- Top_10_Most_Profitable_Products
WITH 
    DIM_PRODUCT AS (
        SELECT * FROM {{ ref('DIM_PRODUCT') }}
    ),

    FACT_SALES AS (
        SELECT * FROM {{ ref('FACT_SALES') }}
    ),

    TOP_10_PRODUCT_PROFITS AS (
        SELECT
            DIM_PRODUCT.PRODUCT_ID,
            DIM_PRODUCT.PRODUCT_NAME,
            ROUND(SUM(FACT_SALES.PROFIT),3) AS TOTAL_PROFIT,
            RANK() OVER (ORDER BY TOTAL_PROFIT DESC) AS PRODUCT_RANK

        FROM FACT_SALES
        LEFT JOIN DIM_PRODUCT 
            ON FACT_SALES.PRODUCT_KEY = DIM_PRODUCT.PRODUCT_KEY
        GROUP BY DIM_PRODUCT.PRODUCT_ID, DIM_PRODUCT.PRODUCT_NAME

    )

SELECT *
FROM TOP_10_PRODUCT_PROFITS
WHERE PRODUCT_RANK <= 10
