-- Top 10 Customers by Total Sales 
WITH 
    DIM_CUSTOMER AS (
        SELECT * FROM {{ ref('DIM_CUSTOMER') }}
    ),

    FACT_SALES AS (
        SELECT * FROM {{ ref('FACT_SALES') }}
    ),

    CUSTOMER_SALES_RANKED AS (

        SELECT

            DIM_CUSTOMER.CUSTOMER_ID,
            SUM(FACT_SALES.SALES) AS TOTAL_SALES,
            RANK() OVER (ORDER BY TOTAL_SALES DESC) AS CUSTOMER_RANK

        FROM FACT_SALES 
        LEFT JOIN DIM_CUSTOMER 
            ON FACT_SALES.CUSTOMER_KEY = DIM_CUSTOMER.CUSTOMER_ID

        GROUP BY DIM_CUSTOMER.CUSTOMER_ID
    )

SELECT *
FROM CUSTOMER_SALES_RANKED
WHERE CUSTOMER_RANK <= 10
