{{ config(materialized='table') }}
with

    NYC_SALES_CLEANEND_SOURCE AS (

        SELECT * 
        
        FROM {{ ref('STG_ABANOUB_NYC_SALES_CLEANEND') }}
    ),

    DIM_SALES_DATE AS (

        SELECT * 
        
        FROM {{ ref('STG_ABANOUB_DIM_SALES_DATE') }}

    ),

    DIM_LOCATION AS (

        SELECT * 
        
        FROM {{ ref('STG_ABANOUB_DIM_LOCATION') }}

    ),

    DIM_PROPERTY_AT_PRESENT AS (

        SELECT * 
        
        FROM {{ ref('STG_ABANOUB_DIM_PROPERTY_AT_PRESENT') }}

    ),

    DIM_PROPERTY_AT_SALE AS (

        SELECT * 
        
        FROM {{ ref('STG_ABANOUB_DIM_PROPERTY_AT_SALE') }}

    ),



    FACT_SALES AS (

        SELECT 

            DIM_SALES_DATE.SALES_DATE_ID,

            DIM_LOCATION.LOCATION_ID,

            DIM_PROPERTY_AT_PRESENT.PROPERTY_AT_PRESENT_ID,

            DIM_PROPERTY_AT_SALE.PROPERTY_AT_SALE_ID,

            NYC_SALES_CLEANEND_SOURCE.ADDRESS,

            NYC_SALES_CLEANEND_SOURCE.APARTMENT_NUMBER,

            NYC_SALES_CLEANEND_SOURCE.TAX_LOT,

            NYC_SALES_CLEANEND_SOURCE.TAX_BLOCK,

            NYC_SALES_CLEANEND_SOURCE.RESIDENTIAL_UNITS,

            NYC_SALES_CLEANEND_SOURCE.COMMERCIAL_UNITS,

            NYC_SALES_CLEANEND_SOURCE.TOTAL_UNITS,

            NYC_SALES_CLEANEND_SOURCE.LAND_SQUARE_FEET,

            NYC_SALES_CLEANEND_SOURCE.GROSS_SQUARE_FEET,

            NYC_SALES_CLEANEND_SOURCE.SALE_PRICE  
        
        FROM NYC_SALES_CLEANEND_SOURCE  

        LEFT JOIN  DIM_LOCATION 
            ON NYC_SALES_CLEANEND_SOURCE.BOROUGH = DIM_LOCATION.BOROUGH 
            AND NYC_SALES_CLEANEND_SOURCE.BOROUGH_NAME = DIM_LOCATION.BOROUGH_NAME 
            AND TRIM(NYC_SALES_CLEANEND_SOURCE.NEIGHBORHOOD) = DIM_LOCATION.NEIGHBORHOOD 
            AND (NYC_SALES_CLEANEND_SOURCE.ZIP_CODE = DIM_LOCATION.ZIP_CODE OR (NYC_SALES_CLEANEND_SOURCE.ZIP_CODE IS NULL AND DIM_LOCATION.ZIP_CODE IS NULL))

        LEFT JOIN DIM_SALES_DATE
            ON NYC_SALES_CLEANEND_SOURCE.SALE_DATE = DIM_SALES_DATE.SALE_DATE

        LEFT JOIN DIM_PROPERTY_AT_PRESENT
                ON NYC_SALES_CLEANEND_SOURCE.BUILDING_CLASS_AT_PRESENT = DIM_PROPERTY_AT_PRESENT.BUILDING_CLASS_AT_PRESENT
                AND NYC_SALES_CLEANEND_SOURCE.TAX_CLASS_AT_PRESENT = DIM_PROPERTY_AT_PRESENT.TAX_CLASS_AT_PRESENT
                AND NYC_SALES_CLEANEND_SOURCE.TAX_SUBCLASS_AT_PRESENT = DIM_PROPERTY_AT_PRESENT.TAX_SUBCLASS_AT_PRESENT

        LEFT JOIN DIM_PROPERTY_AT_SALE
            ON NYC_SALES_CLEANEND_SOURCE.BUILDING_CLASS_CATEGORY = DIM_PROPERTY_AT_SALE.BUILDING_CLASS_CATEGORY
            AND NYC_SALES_CLEANEND_SOURCE.BUILDING_CLASS_AT_TIME_OF_SALE = DIM_PROPERTY_AT_SALE.BUILDING_CLASS_AT_TIME_OF_SALE
            AND NYC_SALES_CLEANEND_SOURCE.TAX_CLASS_AT_TIME_OF_SALE = DIM_PROPERTY_AT_SALE.TAX_CLASS_AT_TIME_OF_SALE
            AND (NYC_SALES_CLEANEND_SOURCE.YEAR_BUILT = DIM_PROPERTY_AT_SALE.YEAR_BUILT OR (NYC_SALES_CLEANEND_SOURCE.YEAR_BUILT IS NULL AND DIM_PROPERTY_AT_SALE.YEAR_BUILT IS NULL))
       
    )

SELECT *
FROM FACT_SALES
