
WITH 

    FACT_SALES AS (
        SELECT * FROM {{ ref('ABANOUB_FACT_SALES') }}
    ),

    AVG_SALE_PRICE_PER_BOROUGH AS (
        SELECT
            L.BOROUGH,
            AVG(F.SALE_PRICE) AS AVERAGE_SALE_PRICE
        FROM
            FACT_SALES F
        INNER JOIN
            STG_ABANOUB_DIM_LOCATION L ON F.LOCATION_ID = L.LOCATION_ID
        GROUP BY
            L.BOROUGH
    )

SELECT
    A.BOROUGH,
    A.AVERAGE_SALE_PRICE
FROM
    AVG_SALE_PRICE_PER_BOROUGH A
ORDER BY A.BOROUGH ASC
