WITH 

    FACT_SALES AS (
        SELECT * FROM {{ ref('ABANOUB_FACT_SALES') }}
    ),

    DIM_PROPERTY_AT_PRESENT  AS (
        SELECT * FROM {{ ref('STG_ABANOUB_DIM_PROPERTY_AT_PRESENT') }}
    ),

    DIM_PROPERTY_AT_SALE  AS (
        SELECT * FROM {{ ref('STG_ABANOUB_DIM_PROPERTY_AT_SALE') }}
    ),

    TAX_CLASS_AT_PRESENT_AVERAGE_SALE_PRICE AS (
        SELECT
            P.TAX_CLASS_AT_PRESENT,
            AVG(F.SALE_PRICE) AS AVERAGE_SALE_PRICE_AT_PRESENT
        FROM
            FACT_SALES F
        INNER JOIN
            DIM_PROPERTY_AT_PRESENT P ON F.PROPERTY_AT_PRESENT_ID = P.PROPERTY_AT_PRESENT_ID
        
        GROUP BY
            P.TAX_CLASS_AT_PRESENT
        ORDER BY P.TAX_CLASS_AT_PRESENT
    ),

    TAX_CLASS_AT_SALE_AVERAGE_SALE_PRICE AS (
        SELECT
            P.TAX_CLASS_AT_TIME_OF_SALE,
            AVG(F.SALE_PRICE) AS AVERAGE_SALE_PRICE_AT_SALE
        FROM
            ABANOUB_FACT_SALES F
        INNER JOIN
            DIM_PROPERTY_AT_SALE P ON F.PROPERTY_AT_SALE_ID = P.PROPERTY_AT_SALE_ID
        
        GROUP BY
            P.TAX_CLASS_AT_TIME_OF_SALE
        ORDER BY P.TAX_CLASS_AT_TIME_OF_SALE
    ),

    FINAL AS (

        SELECT
            TAX_CLASS_AT_PRESENT_AVERAGE_SALE_PRICE.TAX_CLASS_AT_PRESENT,
            TAX_CLASS_AT_PRESENT_AVERAGE_SALE_PRICE.AVERAGE_SALE_PRICE_AT_PRESENT,

            TAX_CLASS_AT_SALE_AVERAGE_SALE_PRICE.TAX_CLASS_AT_TIME_OF_SALE,
            TAX_CLASS_AT_SALE_AVERAGE_SALE_PRICE.AVERAGE_SALE_PRICE_AT_SALE,

            CASE
                WHEN  TAX_CLASS_AT_PRESENT_AVERAGE_SALE_PRICE.AVERAGE_SALE_PRICE_AT_PRESENT >   
                    TAX_CLASS_AT_SALE_AVERAGE_SALE_PRICE.AVERAGE_SALE_PRICE_AT_SALE
                    THEN 'AVERAGE_SALE_PRICE_AT_PRESENT IS GREATER THAN AVERAGE_SALE_PRICE_AT_SALE'
                WHEN TAX_CLASS_AT_PRESENT_AVERAGE_SALE_PRICE.AVERAGE_SALE_PRICE_AT_PRESENT <   
                    TAX_CLASS_AT_SALE_AVERAGE_SALE_PRICE.AVERAGE_SALE_PRICE_AT_SALE
                    THEN 'AVERAGE_SALE_PRICE_AT_PRESENT IS LESS THAN AVERAGE_SALE_PRICE_AT_SALE'
                ELSE 'AVERAGE_SALE_PRICE_AT_PRESENT IS EQUAL TO AVERAGE_SALE_PRICE_AT_SALE'
            END AS COMPARIING_AVERAGE_SALE_PRICE
        FROM
            TAX_CLASS_AT_PRESENT_AVERAGE_SALE_PRICE 

        CROSS JOIN TAX_CLASS_AT_SALE_AVERAGE_SALE_PRICE

        ORDER BY TAX_CLASS_AT_PRESENT_AVERAGE_SALE_PRICE.TAX_CLASS_AT_PRESENT,TAX_CLASS_AT_SALE_AVERAGE_SALE_PRICE.TAX_CLASS_AT_TIME_OF_SALE
    )

SELECT *
FROM FINAL
